apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lavi324-cert
  namespace: default
spec:
  secretName: lavi324-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - lavi324.duckdns.org
