apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: default
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:pwwWmJS5a8@mongodb.mongo.svc.cluster.local:27017"
  MONGO_DB: "sportsdb"
